// <auto-generated />
using System;
using DryClean.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DryClean.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260712192500_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("DryClean.Api.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Line2")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("DryClean.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "shirt",
                            IsActive = true,
                            Name = "Men",
                            Slug = "men",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Icon = "sparkles",
                            IsActive = true,
                            Name = "Women",
                            Slug = "women",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Icon = "baby",
                            IsActive = true,
                            Name = "Kids",
                            Slug = "kids",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Icon = "blinds",
                            IsActive = true,
                            Name = "Curtains",
                            Slug = "curtains",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Icon = "sofa",
                            IsActive = true,
                            Name = "Sofa & Couch Covers",
                            Slug = "sofa-covers",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Icon = "footprints",
                            IsActive = true,
                            Name = "Shoes",
                            Slug = "shoes",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            Icon = "bed",
                            IsActive = true,
                            Name = "Household",
                            Slug = "household",
                            SortOrder = 7
                        });
                });

            modelBuilder.Entity("DryClean.Api.Models.ClothType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .HasMaxLength(800)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerPiece")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Service")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ClothTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Formal or casual shirt",
                            Icon = "shirt",
                            IsActive = true,
                            Name = "Shirt",
                            Overview = "Collars and cuffs pre-treated, hand-finished and pressed.",
                            PricePerPiece = 40m,
                            Service = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Cotton tee",
                            Icon = "shirt",
                            IsActive = true,
                            Name = "T-Shirt",
                            Overview = "Gentle wash that keeps prints and colours intact.",
                            PricePerPiece = 25m,
                            Service = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Formal trousers",
                            Icon = "shirt",
                            IsActive = true,
                            Name = "Trousers / Pants",
                            Overview = "Crease-set and pressed to a sharp finish.",
                            PricePerPiece = 50m,
                            Service = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Denim",
                            Icon = "shirt",
                            IsActive = true,
                            Name = "Jeans",
                            Overview = "Colour-safe wash that protects the indigo.",
                            PricePerPiece = 45m,
                            Service = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Ethnic kurta",
                            Icon = "sparkles",
                            IsActive = true,
                            Name = "Kurta",
                            Overview = "Delicate handling for ethnic fabrics and embroidery.",
                            PricePerPiece = 60m,
                            Service = 1
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Includes roll press",
                            Icon = "sparkles",
                            IsActive = true,
                            Name = "Saree",
                            Overview = "Roll-pressed and stored on a hanger to avoid creases.",
                            PricePerPiece = 120m,
                            Service = 3
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Blazer + trouser",
                            Icon = "sparkles",
                            IsActive = true,
                            Name = "Suit (2 pc)",
                            Overview = "Two-piece dry cleaned together for an even finish.",
                            PricePerPiece = 200m,
                            Service = 3
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Single blazer",
                            Icon = "sparkles",
                            IsActive = true,
                            Name = "Blazer / Coat",
                            Overview = "Structured press that keeps the shoulders sharp.",
                            PricePerPiece = 150m,
                            Service = 1
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 7,
                            Description = "Double bedsheet",
                            Icon = "bed",
                            IsActive = true,
                            Name = "Bedsheet (Double)",
                            Overview = "Hot-wash hygiene wash, neatly folded.",
                            PricePerPiece = 90m,
                            Service = 0
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "Charged per metre",
                            Icon = "blinds",
                            IsActive = true,
                            Name = "Curtain (per m)",
                            Overview = "Dust-extracted and finished to hang crease-free.",
                            PricePerPiece = 70m,
                            Service = 1
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "Winter jacket",
                            Icon = "sparkles",
                            IsActive = true,
                            Name = "Jacket (Woollen)",
                            Overview = "Wool-safe clean that revives loft and warmth.",
                            PricePerPiece = 180m,
                            Service = 3
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Description = "Steam press only",
                            Icon = "flame",
                            IsActive = true,
                            Name = "Iron Only (per pc)",
                            Overview = "Steam-pressed and ready to wear.",
                            PricePerPiece = 10m,
                            Service = 2
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "Children's clothing",
                            Icon = "baby",
                            IsActive = true,
                            Name = "Kids Wear (per pc)",
                            Overview = "Skin-friendly, mild detergents for little ones.",
                            PricePerPiece = 20m,
                            Service = 0
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 6,
                            Description = "Leather, suede or canvas",
                            Icon = "footprints",
                            IsActive = true,
                            Name = "Shoe Cleaning (pair)",
                            Overview = "Deep clean, conditioning and deodorising for one pair.",
                            PricePerPiece = 150m,
                            Service = 3
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Description = "Removable covers",
                            Icon = "sofa",
                            IsActive = true,
                            Name = "Sofa Cover (per seat)",
                            Overview = "Fabric-safe clean per seat cover.",
                            PricePerPiece = 120m,
                            Service = 1
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "Women's dress",
                            Icon = "sparkles",
                            IsActive = true,
                            Name = "Dress / Frock",
                            Overview = "Gentle dry clean for dresses and gowns.",
                            PricePerPiece = 80m,
                            Service = 1
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 7,
                            Description = "Single blanket",
                            Icon = "bed",
                            IsActive = true,
                            Name = "Blanket (Single)",
                            Overview = "Fluff-restoring wash that removes dust and allergens.",
                            PricePerPiece = 150m,
                            Service = 3
                        });
                });

            modelBuilder.Entity("DryClean.Api.Models.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BannerImageUrl")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClothTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<int>("DiscountType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowOnHome")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Target")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ClothTypeId");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "FRESH20",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "New here? Take 20% off your first order.",
                            DiscountType = 0,
                            DiscountValue = 20m,
                            EndsAt = new DateTime(2027, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ShowOnHome = true,
                            StartsAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Target = 0,
                            Title = "20% off your first pickup"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sarees, kurtas and dresses — 15% off this season.",
                            DiscountType = 0,
                            DiscountValue = 15m,
                            EndsAt = new DateTime(2027, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ShowOnHome = true,
                            StartsAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Target = 1,
                            Title = "15% off all Women's wear"
                        });
                });

            modelBuilder.Entity("DryClean.Api.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Channel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DeliveryFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PickupAddressText")
                        .HasColumnType("TEXT");

                    b.Property<double?>("PickupLatitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("PickupLongitude")
                        .HasColumnType("REAL");

                    b.Property<string>("RazorpayOrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RazorpayPaymentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ScheduledPickupAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DryClean.Api.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClothTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClothTypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("DryClean.Api.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderOrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderPaymentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("DryClean.Api.Models.ProcessStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StepNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProcessSteps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pick your items and place an order in under a minute.",
                            Icon = "clipboard-list",
                            IsActive = true,
                            StepNumber = 1,
                            Title = "Book your order"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Our rider collects your clothes at your chosen time.",
                            Icon = "package",
                            IsActive = true,
                            StepNumber = 2,
                            Title = "Doorstep pickup"
                        },
                        new
                        {
                            Id = 3,
                            Description = "We wash, dry-clean and press with fabric-safe care.",
                            Icon = "sparkles",
                            IsActive = true,
                            StepNumber = 3,
                            Title = "Expert cleaning"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Fresh, folded clothes delivered right back to you.",
                            Icon = "home",
                            IsActive = true,
                            StepNumber = 4,
                            Title = "Doorstep delivery"
                        });
                });

            modelBuilder.Entity("DryClean.Api.Models.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Key = "PickupSchedulingEnabled",
                            Value = "false"
                        },
                        new
                        {
                            Key = "BusinessPhone",
                            Value = "+91 90000 00000"
                        },
                        new
                        {
                            Key = "HomeHeadline",
                            Value = "Fresh clothes, without the trip."
                        },
                        new
                        {
                            Key = "ProjectName",
                            Value = "Fresh & Fold"
                        },
                        new
                        {
                            Key = "ProjectDescription",
                            Value = "Pickup & delivery dry cleaning, without the trip."
                        },
                        new
                        {
                            Key = "ProjectIcon",
                            Value = "shirt"
                        });
                });

            modelBuilder.Entity("DryClean.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DryClean.Api.Models.Address", b =>
                {
                    b.HasOne("DryClean.Api.Models.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DryClean.Api.Models.ClothType", b =>
                {
                    b.HasOne("DryClean.Api.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DryClean.Api.Models.Offer", b =>
                {
                    b.HasOne("DryClean.Api.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DryClean.Api.Models.ClothType", "ClothType")
                        .WithMany()
                        .HasForeignKey("ClothTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("ClothType");
                });

            modelBuilder.Entity("DryClean.Api.Models.Order", b =>
                {
                    b.HasOne("DryClean.Api.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DryClean.Api.Models.OrderItem", b =>
                {
                    b.HasOne("DryClean.Api.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DryClean.Api.Models.Payment", b =>
                {
                    b.HasOne("DryClean.Api.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DryClean.Api.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DryClean.Api.Models.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
